"""
PDF exporter using playwright for high-quality PDF generation.
"""

# pylint: disable=broad-exception-caught,duplicate-code

import os
import tempfile
import logging
import base64
from datetime import datetime
from pathlib import Path
from typing import Optional, Dict, Any
from urllib.parse import unquote

from bs4 import BeautifulSoup
from playwright.sync_api import sync_playwright

logger = logging.getLogger(__name__)

# Constants
RENDER_WAIT_MS = 1000  # Wait for diagrams to render


class PDFExporter:
    """Export HTML content to PDF."""

    def __init__(self):
        """Initialize PDF exporter."""
        self.playwright = None
        self.browser = None

    def _ensure_browser(self) -> None:
        """Ensure browser is initialized."""
        if self.playwright is None:
            self.playwright = sync_playwright().start()
            self.browser = self.playwright.chromium.launch()
            logger.info("Playwright browser launched")

    def export(
        self, html_content: str, output_path: str, options: Optional[Dict[str, Any]] = None
    ) -> None:
        """
        Export HTML content to PDF.

        Args:
            html_content: HTML string to export
            output_path: Path to save PDF file
            options: Optional dictionary of PDF options
        """
        if options is None:
            options = {}

        self._ensure_browser()

        # Wrap content if it's not a complete HTML document
        if not html_content.strip().startswith("<!DOCTYPE"):
            html_content = self._wrap_html(html_content)

        # Convert local images to data URLs for PDF rendering
        html_content = self._embed_local_images(html_content, options.get("base_path"))

        # Create a temporary HTML file
        with tempfile.NamedTemporaryFile(
            mode="w", suffix=".html", delete=False, encoding="utf-8"
        ) as f:
            f.write(html_content)
            temp_html = f.name

        # Create new context for isolation
        context = self.browser.new_context()
        try:
            # Create a new page in the context
            page = context.new_page()

            # Navigate to the HTML file
            page.goto(f"file://{temp_html}")

            # Wait for content to render (especially important for diagrams)
            page.wait_for_timeout(RENDER_WAIT_MS)

            # PDF options with footer
            current_datetime = datetime.now().strftime("%B %d, %Y at %I:%M %p")
            pdf_options = {
                "path": output_path,
                "format": options.get("format", "A4"),
                "print_background": True,
                "display_header_footer": True,
                "footer_template": f'<div style="font-size:9px;text-align:center;width:100%;color:#666;">Generated by Markdown Viewer on {current_datetime} - Page <span class="pageNumber"></span> of <span class="totalPages"></span></div>',
                "margin": options.get(
                    "margin", {"top": "1cm", "right": "1cm", "bottom": "1.5cm", "left": "1cm"}
                ),
            }

            # Generate PDF
            page.pdf(**pdf_options)

            page.close()
        finally:
            context.close()
            # Clean up temporary file
            if os.path.exists(temp_html):
                try:
                    os.unlink(temp_html)
                except OSError as e:
                    logger.warning("Failed to delete temp HTML file: %s", e)

    def _embed_local_images(self, html_content: str, base_path: Optional[str] = None) -> str:
        """Convert local file:// images to data URLs for PDF rendering."""
        soup = BeautifulSoup(html_content, "html.parser")
        img_elements = soup.find_all("img")

        for img in img_elements:
            src = img.get("src", "")
            if not src:
                continue

            # Skip remote URLs and data URLs
            if src.startswith(("http://", "https://", "data:")):
                continue

            # It's a local file path - convert to data URL
            try:
                # Decode URL encoding
                decoded_path = unquote(src)

                # Convert to Path object
                img_path = Path(decoded_path)

                # If not absolute, resolve relative to base path
                if not img_path.is_absolute() and base_path:
                    img_path = Path(base_path).parent / decoded_path

                # Read and convert to base64
                if img_path.exists() and img_path.is_file():
                    with open(img_path, "rb") as f:
                        img_data = f.read()

                    # Detect MIME type
                    ext = img_path.suffix.lower()
                    mime_types = {
                        ".png": "image/png",
                        ".jpg": "image/jpeg",
                        ".jpeg": "image/jpeg",
                        ".gif": "image/gif",
                        ".webp": "image/webp",
                        ".svg": "image/svg+xml",
                        ".bmp": "image/bmp",
                    }
                    mime_type = mime_types.get(ext, "image/png")

                    # Convert to data URL
                    b64_data = base64.b64encode(img_data).decode("ascii")
                    data_url = f"data:{mime_type};base64,{b64_data}"

                    # Replace src
                    img["src"] = data_url
                    logger.info("Embedded image: %s (%d KB)", img_path.name, len(img_data) // 1024)
                else:
                    logger.warning("Image file not found: %s", img_path)
            except Exception as e:
                logger.warning("Failed to embed image %s: %s", src, e)

        return str(soup)

    def _wrap_html(self, content):
        """Wrap content in a complete HTML document for PDF generation."""
        # pylint: disable=line-too-long
        return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Markdown Document</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
            line-height: 1.6;
            max-width: 900px;
            margin: 0 auto;
            padding: 20px;
            color: #333;
        }}
        pre {{
            background-color: #f5f5f5;
            padding: 15px;
            border-radius: 5px;
            overflow-x: auto;
        }}
        code {{
            font-family: 'Consolas', 'Monaco', 'Courier New', monospace;
            background-color: #f5f5f5;
            padding: 2px 5px;
            border-radius: 3px;
        }}
        img {{
            max-width: 100%;
            height: auto;
        }}
        table {{
            border-collapse: collapse;
            width: 100%;
            margin: 20px 0;
        }}
        th, td {{
            border: 1px solid #ddd;
            padding: 12px;
            text-align: left;
        }}
        th {{
            background-color: #f5f5f5;
            font-weight: bold;
        }}
        blockquote {{
            border-left: 4px solid #ccc;
            margin: 20px 0;
            padding-left: 20px;
            color: #666;
        }}
        .mermaid {{
            text-align: center;
            margin: 20px 0;
        }}
    </style>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.45/dist/katex.min.css">
    <script src="https://cdn.jsdelivr.net/npm/katex@0.16.45/dist/katex.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/katex@0.16.45/dist/contrib/auto-render.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.min.js"></script>
</head>
<body>
    {content}
    <script>
        // Render KaTeX formulas
        document.addEventListener("DOMContentLoaded", function() {{
            renderMathInElement(document.body, {{
                delimiters: [
                    {{left: '$$', right: '$$', display: true}},
                    {{left: '\\\\[', right: '\\\\]', display: true}},
                    {{left: '$', right: '$', display: false}},
                    {{left: '\\\\(', right: '\\\\)', display: false}}
                ],
                throwOnError: false
            }});
        }});

        // Render Mermaid diagrams
        (async function() {{
            var diagrams = document.querySelectorAll('.mermaid');
            if (!diagrams.length) return;
            function decodeEntities(str) {{
                return str.replace(/&amp;/g, '&').replace(/&lt;/g, '<')
                          .replace(/&gt;/g, '>').replace(/&quot;/g, '"').replace(/&#39;/g, "'");
            }}
            mermaid.initialize({{
                startOnLoad: false,
                theme: 'default',
                securityLevel: 'loose',
                suppressErrors: true
            }});
            for (var i = 0; i < diagrams.length; i++) {{
                var el = diagrams[i];
                var source = decodeEntities((el.textContent || '').trim());
                el.textContent = source;
                try {{
                    var id = 'mermaid-' + Date.now() + '-' + i;
                    var result = await mermaid.render(id, source);
                    el.innerHTML = result.svg;
                }} catch (e) {{
                    var escaped = source.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
                    el.innerHTML = '<details style="border:1px solid #fca;background:#fff8f5;border-radius:4px;padding:8px">'
                        + '<summary style="cursor:pointer;color:#c60;font-weight:bold">'
                        + '\u26a0 Diagram could not be rendered (click to view source)</summary>'
                        + '<pre style="margin:8px 0 0;overflow:auto;font-size:13px">' + escaped + '</pre></details>';
                    console.warn('Mermaid render failed:', e.message || e);
                }}
            }}
        }})();
    </script>
</body>
</html>"""

    def close(self) -> None:
        """Explicitly close browser and playwright."""
        if self.browser:
            try:
                self.browser.close()
                logger.info("Browser closed")
            except Exception as e:
                # Event loop closed errors are expected during cleanup, ignore them
                if "Event loop is closed" not in str(e):
                    logger.warning("Error closing browser: %s", e)
            finally:
                self.browser = None

        if self.playwright:
            try:
                self.playwright.stop()
                logger.info("Playwright stopped")
            except Exception as e:
                # Event loop closed errors are expected during cleanup, ignore them
                if "Event loop is closed" not in str(e):
                    logger.warning("Error stopping playwright: %s", e)
            finally:
                self.playwright = None

    def __enter__(self):
        """Context manager entry."""
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        """Context manager exit with cleanup."""
        self.close()
        return False

    def __del__(self):
        """Clean up resources on deletion."""
        # Note: __del__ is unreliable, prefer explicit close() or context manager
        self.close()
